version: '3.8'

services:
  hadoop:
    image: marcelmittelstaedt/spark_base:latest
    platform: linux/amd64
    container_name: hadoop
    ports:
      - "8088:8080"  # Resource Manager
      - "9870:9870"  # HDFS NameNode UI
      - "9864:9864"  # HDFS Secondary NameNode
      - "8888:8888"  # Spark UI (if Spark is part of your Hadoop image)
      - "9000:9000"  # HDFS Data access
    volumes:
      - ./hadoop:/usr/local/hadoop
    networks:
      - pipeline-net
    command: /bin/bash -c "start-dfs.sh && start-yarn.sh && tail -f /dev/null"  # Start Hadoop services and keep container running

networks:
  pipeline-net:
    driver: bridge
